#aqui colocamos as configs do projeto, por isso aq fica a conexão do db, pois não é codigo com logica

#spring.application.name=telaLoginMat
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=telaLoginMat

#atenção!!
# .data é pra configurar como o spring trabalha com a conexao ja existstente 
# .mongo diretamente agnt vai configurar qual porta vamos entrar
# anteriormente colocavamos data cm as infos da porta, oq o spring nao entendia e salvava os dados no banco de teste em vez de user

spring.application.name=telaLoginMat

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=telaLoginMat